dbfilename redis_queue.rdb
dir /home/quoc/GitHub_QLDA_22NH10_G12_BTQT/frappe-bench/config/pids
pidfile /home/quoc/GitHub_QLDA_22NH10_G12_BTQT/frappe-bench/config/pids/redis_queue.pid
bind 127.0.0.1
port 11000

aclfile /home/quoc/GitHub_QLDA_22NH10_G12_BTQT/frappe-bench/config/redis_queue.acl
